---
name: "Recording Manager"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Adds functionality to improve the user experience of recording Live TV."
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "Live TV"
owner: "Samira"
artifacts:
- "Jellyfin.Plugin.RecordingManager.dll"
changelog: >
  changelog